<a href="https://colab.research.google.com/github/anujdutt9/Deep-Learning-TF-2.0/blob/master/TF_2_0_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Setting up TensorFlow 2.0

In [0]:
# Install Latest Version of TensorFlow
#!pip install tensorflow-gpu --upgrade

In [0]:
# Import TensorFlow 2.0
import tensorflow as tf
import numpy as np

In [3]:
# Check TensorFlow Version
print("TensorFlow Version: ", tf.__version__)

TensorFlow Version:  2.0.0


# 2. Defining a Constant

## Constant in TF 2.0

In [4]:
# Define a constant
tensor = tf.constant([[1,2,3],[4,5,6]])
tensor

<tf.Tensor: id=0, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [5]:
# Shape of Constant Tensor
tensor.shape

TensorShape([2, 3])

## TensorFlow to Numpy Array

In [6]:
# Getting Values of Tensor as Numpy Array
tensor.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

## Numpy Array to TensorFlow Tensor

In [7]:
# Numpy Array to TF Tensor
np_tensor = np.array([[1,3], [5,7]])
np_tensor

array([[1, 3],
       [5, 7]])

In [8]:
# Numpy to TensorFlow Tensor
np_to_tf = tf.constant(np_tensor)
np_to_tf

<tf.Tensor: id=1, shape=(2, 2), dtype=int64, numpy=
array([[1, 3],
       [5, 7]])>

# 3. Defining a Variable

In [9]:
# Defining a TF Variable
tf_variable = tf.Variable([[1,3,5], [2,4,6]])
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

## Converting TF Variable to Numpy Array

In [10]:
# Converting to Numpy
tf_variable.numpy()

array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)

In [11]:
# Changing a Specific value in Tensor Variable
# Changing value at Row 0 and Column 2 to 100.
tf_variable[0,2].assign(100)
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[  1,   3, 100],
       [  2,   4,   6]], dtype=int32)>

# 4. Operations with Tensors

In [12]:
# Sample Constant Tensor
tensor = tf.constant([[1,2], [3,4]])
tensor

<tf.Tensor: id=19, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

## Addition

In [13]:
# Add a scalar value to tensor
tensor + 2

<tf.Tensor: id=21, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

## Invalid Operation

In [14]:
# Adding a value of different data type gives an error.
tensor + 3.0

InvalidArgumentError: ignored

## Multiplication

In [15]:
# Multiplying tensor with a scalar
tensor * 9

<tf.Tensor: id=25, shape=(2, 2), dtype=int32, numpy=
array([[ 9, 18],
       [27, 36]], dtype=int32)>

## Numpy Operations on Tensor

In [16]:
# Getting squares of all numbers in tensor
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [17]:
# Getting Square root of Tensor Values
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [18]:
# Adding Numpy Array to Tensor
np.ones((2,2)) + tensor

<tf.Tensor: id=27, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [19]:
# Multiplying Numpy Array values to Tensor
np.linspace(0, 12, 4).reshape(2,2) * tensor

<tf.Tensor: id=29, shape=(2, 2), dtype=int32, numpy=
array([[ 0,  8],
       [24, 48]], dtype=int32)>

In [20]:
# Dot Product of two tensors
np.dot(tensor, tensor)

array([[ 7, 10],
       [15, 22]], dtype=int32)

# 5. Strings in TensorFlow 2.0

In [21]:
# Create a String
tf_string = tf.constant("Hello World. This is TensorFlow 2.0.")
tf_string

<tf.Tensor: id=30, shape=(), dtype=string, numpy=b'Hello World. This is TensorFlow 2.0.'>

In [22]:
# Length of String
tf.strings.length(tf_string)

<tf.Tensor: id=31, shape=(), dtype=int32, numpy=36>

In [23]:
# Decode string to UTF-8 format
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=35, shape=(36,), dtype=int32, numpy=
array([ 72, 101, 108, 108, 111,  32,  87, 111, 114, 108, 100,  46,  32,
        84, 104, 105, 115,  32, 105, 115,  32,  84, 101, 110, 115, 111,
       114,  70, 108, 111, 119,  32,  50,  46,  48,  46], dtype=int32)>

In [24]:
# Storing Arrays of String
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "Machine Learning"])
tf_string_array

<tf.Tensor: id=36, shape=(3,), dtype=string, numpy=array([b'TensorFlow', b'Deep Learning', b'Machine Learning'], dtype=object)>

In [25]:
# Iterating through the TF String Array
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'Machine Learning', shape=(), dtype=string)
